package ui

import "github.com/charmbracelet/lipgloss"

type Theme struct {
	Border  lipgloss.Color
	Title   lipgloss.Color
	Info    lipgloss.Color
	Meter   lipgloss.Color
	Log     lipgloss.Color
	Help    lipgloss.Color
	Online  lipgloss.Color
	Offline lipgloss.Color
	Dim     lipgloss.Color
}

var themeNames = []string{

	"Lavender", "Sage", "Steel", "Dust", "Rose", "Peach",

	"Neon Purple", "Neon Green", "Neon Blue", "Neon Red",

	"Monochrome", "High Contrast",

	"Ocean", "Arctic", "Moss", "Copper", "Ember",

	"Dusk", "Dracula", "Solarized", "Terminal", "Candy",

	"Aurora", "Volcano", "Matrix", "Midnight Gold", "Glacier", "Sakura Night",
	"Toxic Lime", "Royal Indigo", "Retro Sunset", "Noir Crimson", "Mint Chip", "Electric Mango",

	"Nord", "Gruvbox Dark", "Catppuccin Mocha", "One Dark Pro", "Tokyo Night",
	"Monokai Pro", "Everforest Dark", "Kanagawa Wave", "GitHub Dark", "Night Owl",

	"VHS Dream", "Arcade Night", "Pixel Sunrise", "Retro Neon Grid", "CRT Glow",
	"Floppy Diskette", "Synth Arcade", "8-Bit Dusk", "Retro Electro", "Cassette Blaze",
	"Laser Arcade", "Retro Waveform", "Neon Cartridge", "Analog Sunset", "Pixel Noir",
}

var themes = []Theme{
	// 0: Lavender (Muted Purple)
	{
		Border:  lipgloss.Color("#9b7bb0"),
		Title:   lipgloss.Color("#bba8cd"),
		Info:    lipgloss.Color("#a794b9"),
		Meter:   lipgloss.Color("#c7b6d9"),
		Log:     lipgloss.Color("#8c799c"),
		Help:    lipgloss.Color("#6f5a7e"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#b87474"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 1: Sage (Muted Green)
	{
		Border:  lipgloss.Color("#7fb08c"),
		Title:   lipgloss.Color("#a8cdb6"),
		Info:    lipgloss.Color("#94b9a4"),
		Meter:   lipgloss.Color("#b6d9c6"),
		Log:     lipgloss.Color("#799c87"),
		Help:    lipgloss.Color("#5a7e68"),
		Online:  lipgloss.Color("#7fb08c"),
		Offline: lipgloss.Color("#b87474"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 2: Steel (Muted Blue)
	{
		Border:  lipgloss.Color("#7894b8"),
		Title:   lipgloss.Color("#a3c1e0"),
		Info:    lipgloss.Color("#89a5c4"),
		Meter:   lipgloss.Color("#b1cced"),
		Log:     lipgloss.Color("#6b85a3"),
		Help:    lipgloss.Color("#4c6685"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#b87474"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 3: Dust (Muted Grey/Cyan)
	{
		Border:  lipgloss.Color("#889c9c"),
		Title:   lipgloss.Color("#b3c3c3"),
		Info:    lipgloss.Color("#98abab"),
		Meter:   lipgloss.Color("#bfd0d0"),
		Log:     lipgloss.Color("#768a8a"),
		Help:    lipgloss.Color("#5b6f6f"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#b87474"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 4: Rose (Muted Pink/Red)
	{
		Border:  lipgloss.Color("#bd818f"),
		Title:   lipgloss.Color("#dbaabb"),
		Info:    lipgloss.Color("#c494a0"),
		Meter:   lipgloss.Color("#deb6c3"),
		Log:     lipgloss.Color("#a36e7a"),
		Help:    lipgloss.Color("#85525d"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 5: Peach (Muted Orange/Pink)
	{
		Border:  lipgloss.Color("#c79a83"),
		Title:   lipgloss.Color("#dec1b0"),
		Info:    lipgloss.Color("#cca897"),
		Meter:   lipgloss.Color("#e6d1c5"),
		Log:     lipgloss.Color("#b3836d"),
		Help:    lipgloss.Color("#8a5d48"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 6: Neon Purple
	{
		Border:  lipgloss.Color("#8A2BE2"),
		Title:   lipgloss.Color("#D2A8FF"),
		Info:    lipgloss.Color("#9D72C3"),
		Meter:   lipgloss.Color("#C77DF3"),
		Log:     lipgloss.Color("#7B52AB"),
		Help:    lipgloss.Color("#5B3285"),
		Online:  lipgloss.Color("#4CAF50"),
		Offline: lipgloss.Color("#F44336"),
		Dim:     lipgloss.Color("#555555"),
	},
	// 7: Neon Green
	{
		Border:  lipgloss.Color("#00FF00"),
		Title:   lipgloss.Color("#A8FFD2"),
		Info:    lipgloss.Color("#72C39D"),
		Meter:   lipgloss.Color("#7DF3C7"),
		Log:     lipgloss.Color("#52AB7B"),
		Help:    lipgloss.Color("#32855B"),
		Online:  lipgloss.Color("#00FF00"),
		Offline: lipgloss.Color("#FF0000"),
		Dim:     lipgloss.Color("#555555"),
	},
	// 8: Neon Blue
	{
		Border:  lipgloss.Color("#0000FF"),
		Title:   lipgloss.Color("#A8D2FF"),
		Info:    lipgloss.Color("#729DC3"),
		Meter:   lipgloss.Color("#7DC7F3"),
		Log:     lipgloss.Color("#527BAB"),
		Help:    lipgloss.Color("#325B85"),
		Online:  lipgloss.Color("#4CAF50"),
		Offline: lipgloss.Color("#F44336"),
		Dim:     lipgloss.Color("#555555"),
	},
	// 9: Neon Red
	{
		Border:  lipgloss.Color("#FF0000"),
		Title:   lipgloss.Color("#FFA8A8"),
		Info:    lipgloss.Color("#C37272"),
		Meter:   lipgloss.Color("#F37D7D"),
		Log:     lipgloss.Color("#AB5252"),
		Help:    lipgloss.Color("#853232"),
		Online:  lipgloss.Color("#4CAF50"),
		Offline: lipgloss.Color("#FF0000"),
		Dim:     lipgloss.Color("#555555"),
	},
	// 10: Monochrome
	{
		Border:  lipgloss.Color("#CCCCCC"),
		Title:   lipgloss.Color("#FFFFFF"),
		Info:    lipgloss.Color("#AAAAAA"),
		Meter:   lipgloss.Color("#DDDDDD"),
		Log:     lipgloss.Color("#888888"),
		Help:    lipgloss.Color("#666666"),
		Online:  lipgloss.Color("#AAAAAA"),
		Offline: lipgloss.Color("#666666"),
		Dim:     lipgloss.Color("#444444"),
	},
	// 11: High Contrast
	{
		Border:  lipgloss.Color("#FFFFFF"),
		Title:   lipgloss.Color("#FFFFFF"),
		Info:    lipgloss.Color("#FFFFFF"),
		Meter:   lipgloss.Color("#FFFFFF"),
		Log:     lipgloss.Color("#FFFFFF"),
		Help:    lipgloss.Color("#FFFFFF"),
		Online:  lipgloss.Color("#FFFFFF"),
		Offline: lipgloss.Color("#FFFFFF"),
		Dim:     lipgloss.Color("#FFFFFF"),
	},
	// 12: Ocean (Deep Blue/Teal)
	{
		Border:  lipgloss.Color("#4a9aba"),
		Title:   lipgloss.Color("#7dcce0"),
		Info:    lipgloss.Color("#5db0c8"),
		Meter:   lipgloss.Color("#9dd8e8"),
		Log:     lipgloss.Color("#3a7a94"),
		Help:    lipgloss.Color("#2a5a6e"),
		Online:  lipgloss.Color("#5dbf8a"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 13: Arctic (Icy blue/white)
	{
		Border:  lipgloss.Color("#90c8d8"),
		Title:   lipgloss.Color("#c8e8f0"),
		Info:    lipgloss.Color("#a8d8e8"),
		Meter:   lipgloss.Color("#d8f0f8"),
		Log:     lipgloss.Color("#6aacbc"),
		Help:    lipgloss.Color("#4a8898"),
		Online:  lipgloss.Color("#78cc9a"),
		Offline: lipgloss.Color("#c87878"),
		Dim:     lipgloss.Color("#606060"),
	},
	// 14: Moss (Dark earthy green)
	{
		Border:  lipgloss.Color("#6b8c5a"),
		Title:   lipgloss.Color("#9ab88a"),
		Info:    lipgloss.Color("#7da068"),
		Meter:   lipgloss.Color("#b2cc9a"),
		Log:     lipgloss.Color("#526b42"),
		Help:    lipgloss.Color("#3a4e2e"),
		Online:  lipgloss.Color("#a0c878"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 15: Copper (Warm metallic)
	{
		Border:  lipgloss.Color("#b87333"),
		Title:   lipgloss.Color("#d4a55a"),
		Info:    lipgloss.Color("#c48840"),
		Meter:   lipgloss.Color("#e8c080"),
		Log:     lipgloss.Color("#8a5520"),
		Help:    lipgloss.Color("#5e3510"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 16: Ember (Dark Orange/Amber)
	{
		Border:  lipgloss.Color("#c87941"),
		Title:   lipgloss.Color("#e8b87a"),
		Info:    lipgloss.Color("#d4955a"),
		Meter:   lipgloss.Color("#f0ce9a"),
		Log:     lipgloss.Color("#a85f2e"),
		Help:    lipgloss.Color("#7a4018"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#c96969"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 17: Dusk (Purple/Blue twilight)
	{
		Border:  lipgloss.Color("#6a6aab"),
		Title:   lipgloss.Color("#a0a0d8"),
		Info:    lipgloss.Color("#8080bc"),
		Meter:   lipgloss.Color("#b8b8e8"),
		Log:     lipgloss.Color("#505090"),
		Help:    lipgloss.Color("#383878"),
		Online:  lipgloss.Color("#7ab087"),
		Offline: lipgloss.Color("#b87474"),
		Dim:     lipgloss.Color("#5a5a5a"),
	},
	// 18: Dracula (Popular dark theme)
	{
		Border:  lipgloss.Color("#bd93f9"),
		Title:   lipgloss.Color("#f8f8f2"),
		Info:    lipgloss.Color("#8be9fd"),
		Meter:   lipgloss.Color("#ff79c6"),
		Log:     lipgloss.Color("#6272a4"),
		Help:    lipgloss.Color("#44475a"),
		Online:  lipgloss.Color("#50fa7b"),
		Offline: lipgloss.Color("#ff5555"),
		Dim:     lipgloss.Color("#44475a"),
	},
	// 19: Solarized (Warm dark)
	{
		Border:  lipgloss.Color("#268bd2"),
		Title:   lipgloss.Color("#2aa198"),
		Info:    lipgloss.Color("#859900"),
		Meter:   lipgloss.Color("#b58900"),
		Log:     lipgloss.Color("#657b83"),
		Help:    lipgloss.Color("#586e75"),
		Online:  lipgloss.Color("#859900"),
		Offline: lipgloss.Color("#dc322f"),
		Dim:     lipgloss.Color("#073642"),
	},
	// 20: Terminal (Classic green-on-black CRT)
	{
		Border:  lipgloss.Color("#00aa00"),
		Title:   lipgloss.Color("#00ff00"),
		Info:    lipgloss.Color("#00cc00"),
		Meter:   lipgloss.Color("#00dd00"),
		Log:     lipgloss.Color("#008800"),
		Help:    lipgloss.Color("#006600"),
		Online:  lipgloss.Color("#00ff00"),
		Offline: lipgloss.Color("#aa0000"),
		Dim:     lipgloss.Color("#004400"),
	},
	// 21: Candy (Bright pastels)
	{
		Border:  lipgloss.Color("#ff8fab"),
		Title:   lipgloss.Color("#ffc8dd"),
		Info:    lipgloss.Color("#ffafcc"),
		Meter:   lipgloss.Color("#bde0fe"),
		Log:     lipgloss.Color("#a2d2ff"),
		Help:    lipgloss.Color("#cdb4db"),
		Online:  lipgloss.Color("#a8dadc"),
		Offline: lipgloss.Color("#e76f51"),
		Dim:     lipgloss.Color("#606060"),
	},
	// 22: Aurora (Vivid polar lights)
	{
		Border:  lipgloss.Color("#39d0ff"),
		Title:   lipgloss.Color("#8cf7ff"),
		Info:    lipgloss.Color("#62e7e2"),
		Meter:   lipgloss.Color("#7bffb7"),
		Log:     lipgloss.Color("#3ca0b8"),
		Help:    lipgloss.Color("#2b6f82"),
		Online:  lipgloss.Color("#52ff9a"),
		Offline: lipgloss.Color("#ff5f73"),
		Dim:     lipgloss.Color("#4a5d66"),
	},
	// 23: Volcano (Lava and basalt)
	{
		Border:  lipgloss.Color("#ff5c33"),
		Title:   lipgloss.Color("#ffc08a"),
		Info:    lipgloss.Color("#ff8b5f"),
		Meter:   lipgloss.Color("#ffd166"),
		Log:     lipgloss.Color("#b54a2e"),
		Help:    lipgloss.Color("#7c2f20"),
		Online:  lipgloss.Color("#9be564"),
		Offline: lipgloss.Color("#ff3b30"),
		Dim:     lipgloss.Color("#5b4a45"),
	},
	// 24: Matrix (Cyber green terminal)
	{
		Border:  lipgloss.Color("#00d100"),
		Title:   lipgloss.Color("#8cff8c"),
		Info:    lipgloss.Color("#4dff6a"),
		Meter:   lipgloss.Color("#adff2f"),
		Log:     lipgloss.Color("#2ea83a"),
		Help:    lipgloss.Color("#1c6f29"),
		Online:  lipgloss.Color("#67ff5a"),
		Offline: lipgloss.Color("#ff4f4f"),
		Dim:     lipgloss.Color("#335033"),
	},
	// 25: Midnight Gold (Dark luxury)
	{
		Border:  lipgloss.Color("#d4af37"),
		Title:   lipgloss.Color("#f6e27a"),
		Info:    lipgloss.Color("#e0c15b"),
		Meter:   lipgloss.Color("#ffd700"),
		Log:     lipgloss.Color("#a8892f"),
		Help:    lipgloss.Color("#7a6222"),
		Online:  lipgloss.Color("#7bcf7b"),
		Offline: lipgloss.Color("#d95a5a"),
		Dim:     lipgloss.Color("#5f5540"),
	},
	// 26: Glacier (Frosted cyan)
	{
		Border:  lipgloss.Color("#7fdfff"),
		Title:   lipgloss.Color("#d8f6ff"),
		Info:    lipgloss.Color("#a6ebff"),
		Meter:   lipgloss.Color("#c1f3ff"),
		Log:     lipgloss.Color("#6bb7cf"),
		Help:    lipgloss.Color("#4a8092"),
		Online:  lipgloss.Color("#89e8b5"),
		Offline: lipgloss.Color("#e07b7b"),
		Dim:     lipgloss.Color("#5e6a70"),
	},
	// 27: Sakura Night (Pink and plum)
	{
		Border:  lipgloss.Color("#ff77b7"),
		Title:   lipgloss.Color("#ffd3ea"),
		Info:    lipgloss.Color("#ff9dcc"),
		Meter:   lipgloss.Color("#ffc0f0"),
		Log:     lipgloss.Color("#b36088"),
		Help:    lipgloss.Color("#7e3f61"),
		Online:  lipgloss.Color("#8edfa3"),
		Offline: lipgloss.Color("#ff6b6b"),
		Dim:     lipgloss.Color("#6b5262"),
	},
	// 28: Toxic Lime (Acid green)
	{
		Border:  lipgloss.Color("#b7ff00"),
		Title:   lipgloss.Color("#e7ff87"),
		Info:    lipgloss.Color("#d4ff3f"),
		Meter:   lipgloss.Color("#f1ff9e"),
		Log:     lipgloss.Color("#89b82b"),
		Help:    lipgloss.Color("#5f8020"),
		Online:  lipgloss.Color("#7fff5a"),
		Offline: lipgloss.Color("#ff5d5d"),
		Dim:     lipgloss.Color("#59664a"),
	},
	// 29: Royal Indigo (Regal violet/blue)
	{
		Border:  lipgloss.Color("#5a4bff"),
		Title:   lipgloss.Color("#c4bbff"),
		Info:    lipgloss.Color("#8f84ff"),
		Meter:   lipgloss.Color("#b5a9ff"),
		Log:     lipgloss.Color("#4f45b8"),
		Help:    lipgloss.Color("#3b337f"),
		Online:  lipgloss.Color("#6fd98f"),
		Offline: lipgloss.Color("#f06363"),
		Dim:     lipgloss.Color("#57546d"),
	},
	// 30: Retro Sunset (Synthwave orange/magenta)
	{
		Border:  lipgloss.Color("#ff6f3c"),
		Title:   lipgloss.Color("#ffb36b"),
		Info:    lipgloss.Color("#ff8d52"),
		Meter:   lipgloss.Color("#ff4fd8"),
		Log:     lipgloss.Color("#b85a3a"),
		Help:    lipgloss.Color("#803d2a"),
		Online:  lipgloss.Color("#73e38f"),
		Offline: lipgloss.Color("#ff5c7a"),
		Dim:     lipgloss.Color("#66504d"),
	},
	// 31: Noir Crimson (Dark with red accents)
	{
		Border:  lipgloss.Color("#b22234"),
		Title:   lipgloss.Color("#ffd1d6"),
		Info:    lipgloss.Color("#e66f7f"),
		Meter:   lipgloss.Color("#ff8fa3"),
		Log:     lipgloss.Color("#8b1f2a"),
		Help:    lipgloss.Color("#611620"),
		Online:  lipgloss.Color("#5fd48b"),
		Offline: lipgloss.Color("#ff4757"),
		Dim:     lipgloss.Color("#5c4a4e"),
	},
	// 32: Mint Chip (Cool mint and chocolate)
	{
		Border:  lipgloss.Color("#4ec5a4"),
		Title:   lipgloss.Color("#c6ffe9"),
		Info:    lipgloss.Color("#86e6c9"),
		Meter:   lipgloss.Color("#9cf5d9"),
		Log:     lipgloss.Color("#3c8f79"),
		Help:    lipgloss.Color("#2c6657"),
		Online:  lipgloss.Color("#7be495"),
		Offline: lipgloss.Color("#e06c75"),
		Dim:     lipgloss.Color("#4f5c58"),
	},
	// 33: Electric Mango (Hot orange/yellow)
	{
		Border:  lipgloss.Color("#ff9f1c"),
		Title:   lipgloss.Color("#ffe08a"),
		Info:    lipgloss.Color("#ffc35a"),
		Meter:   lipgloss.Color("#ffd60a"),
		Log:     lipgloss.Color("#b87316"),
		Help:    lipgloss.Color("#805010"),
		Online:  lipgloss.Color("#7fdc72"),
		Offline: lipgloss.Color("#f25f5c"),
		Dim:     lipgloss.Color("#675843"),
	},
	// 34: Nord
	{
		Border:  lipgloss.Color("#81A1C1"),
		Title:   lipgloss.Color("#ECEFF4"),
		Info:    lipgloss.Color("#88C0D0"),
		Meter:   lipgloss.Color("#8FBCBB"),
		Log:     lipgloss.Color("#5E81AC"),
		Help:    lipgloss.Color("#4C566A"),
		Online:  lipgloss.Color("#A3BE8C"),
		Offline: lipgloss.Color("#BF616A"),
		Dim:     lipgloss.Color("#434C5E"),
	},
	// 35: Gruvbox Dark
	{
		Border:  lipgloss.Color("#D79921"),
		Title:   lipgloss.Color("#FBF1C7"),
		Info:    lipgloss.Color("#83A598"),
		Meter:   lipgloss.Color("#FABD2F"),
		Log:     lipgloss.Color("#B57614"),
		Help:    lipgloss.Color("#665C54"),
		Online:  lipgloss.Color("#B8BB26"),
		Offline: lipgloss.Color("#FB4934"),
		Dim:     lipgloss.Color("#504945"),
	},
	// 36: Catppuccin Mocha
	{
		Border:  lipgloss.Color("#89B4FA"),
		Title:   lipgloss.Color("#CDD6F4"),
		Info:    lipgloss.Color("#94E2D5"),
		Meter:   lipgloss.Color("#F5C2E7"),
		Log:     lipgloss.Color("#7F849C"),
		Help:    lipgloss.Color("#6C7086"),
		Online:  lipgloss.Color("#A6E3A1"),
		Offline: lipgloss.Color("#F38BA8"),
		Dim:     lipgloss.Color("#585B70"),
	},
	// 37: One Dark Pro
	{
		Border:  lipgloss.Color("#61AFEF"),
		Title:   lipgloss.Color("#ABB2BF"),
		Info:    lipgloss.Color("#56B6C2"),
		Meter:   lipgloss.Color("#C678DD"),
		Log:     lipgloss.Color("#5C6370"),
		Help:    lipgloss.Color("#4B5263"),
		Online:  lipgloss.Color("#98C379"),
		Offline: lipgloss.Color("#E06C75"),
		Dim:     lipgloss.Color("#3E4452"),
	},
	// 38: Tokyo Night
	{
		Border:  lipgloss.Color("#7AA2F7"),
		Title:   lipgloss.Color("#C0CAF5"),
		Info:    lipgloss.Color("#7DCFFF"),
		Meter:   lipgloss.Color("#BB9AF7"),
		Log:     lipgloss.Color("#565F89"),
		Help:    lipgloss.Color("#414868"),
		Online:  lipgloss.Color("#9ECE6A"),
		Offline: lipgloss.Color("#F7768E"),
		Dim:     lipgloss.Color("#3B4261"),
	},
	// 39: Monokai Pro
	{
		Border:  lipgloss.Color("#FFD866"),
		Title:   lipgloss.Color("#FCFCFA"),
		Info:    lipgloss.Color("#78DCE8"),
		Meter:   lipgloss.Color("#AB9DF2"),
		Log:     lipgloss.Color("#A9DC76"),
		Help:    lipgloss.Color("#727072"),
		Online:  lipgloss.Color("#A9DC76"),
		Offline: lipgloss.Color("#FF6188"),
		Dim:     lipgloss.Color("#5B595C"),
	},
	// 40: Everforest Dark
	{
		Border:  lipgloss.Color("#A7C080"),
		Title:   lipgloss.Color("#D3C6AA"),
		Info:    lipgloss.Color("#7FBBB3"),
		Meter:   lipgloss.Color("#DBBC7F"),
		Log:     lipgloss.Color("#83C092"),
		Help:    lipgloss.Color("#5C6A72"),
		Online:  lipgloss.Color("#A7C080"),
		Offline: lipgloss.Color("#E67E80"),
		Dim:     lipgloss.Color("#475258"),
	},
	// 41: Kanagawa Wave
	{
		Border:  lipgloss.Color("#7E9CD8"),
		Title:   lipgloss.Color("#DCD7BA"),
		Info:    lipgloss.Color("#7FB4CA"),
		Meter:   lipgloss.Color("#957FB8"),
		Log:     lipgloss.Color("#98BB6C"),
		Help:    lipgloss.Color("#727169"),
		Online:  lipgloss.Color("#98BB6C"),
		Offline: lipgloss.Color("#E46876"),
		Dim:     lipgloss.Color("#54546D"),
	},
	// 42: GitHub Dark
	{
		Border:  lipgloss.Color("#58A6FF"),
		Title:   lipgloss.Color("#C9D1D9"),
		Info:    lipgloss.Color("#79C0FF"),
		Meter:   lipgloss.Color("#A371F7"),
		Log:     lipgloss.Color("#8B949E"),
		Help:    lipgloss.Color("#6E7681"),
		Online:  lipgloss.Color("#3FB950"),
		Offline: lipgloss.Color("#F85149"),
		Dim:     lipgloss.Color("#484F58"),
	},
	// 43: Night Owl
	{
		Border:  lipgloss.Color("#82AAFF"),
		Title:   lipgloss.Color("#D6DEEB"),
		Info:    lipgloss.Color("#7FDBCA"),
		Meter:   lipgloss.Color("#C792EA"),
		Log:     lipgloss.Color("#7FDBCA"),
		Help:    lipgloss.Color("#637777"),
		Online:  lipgloss.Color("#22DA6E"),
		Offline: lipgloss.Color("#FF5874"),
		Dim:     lipgloss.Color("#4B6479"),
	},
	// 44: VHS Dream
	{
		Border:  lipgloss.Color("#5B2F8E"),
		Title:   lipgloss.Color("#FAF3D6"),
		Info:    lipgloss.Color("#FFC4E3"),
		Meter:   lipgloss.Color("#F45BA5"),
		Log:     lipgloss.Color("#26123D"),
		Help:    lipgloss.Color("#140B24"),
		Online:  lipgloss.Color("#F6D27E"),
		Offline: lipgloss.Color("#F45BA5"),
		Dim:     lipgloss.Color("#05030A"),
	},
	// 45: Arcade Night
	{
		Border:  lipgloss.Color("#1F2E63"),
		Title:   lipgloss.Color("#F5F9FF"),
		Info:    lipgloss.Color("#27E8F2"),
		Meter:   lipgloss.Color("#FF2F92"),
		Log:     lipgloss.Color("#18224A"),
		Help:    lipgloss.Color("#121733"),
		Online:  lipgloss.Color("#FFDA3A"),
		Offline: lipgloss.Color("#FF2F92"),
		Dim:     lipgloss.Color("#050710"),
	},
	// 46: Pixel Sunrise
	{
		Border:  lipgloss.Color("#4A215E"),
		Title:   lipgloss.Color("#FFF7E3"),
		Info:    lipgloss.Color("#FFE79B"),
		Meter:   lipgloss.Color("#F24876"),
		Log:     lipgloss.Color("#301743"),
		Help:    lipgloss.Color("#1A1129"),
		Online:  lipgloss.Color("#FFC561"),
		Offline: lipgloss.Color("#F24876"),
		Dim:     lipgloss.Color("#05040A"),
	},
	// 47: Retro Neon Grid
	{
		Border:  lipgloss.Color("#181F63"),
		Title:   lipgloss.Color("#F4F8FF"),
		Info:    lipgloss.Color("#22E0FF"),
		Meter:   lipgloss.Color("#FF3FD1"),
		Log:     lipgloss.Color("#11154A"),
		Help:    lipgloss.Color("#0B0E35"),
		Online:  lipgloss.Color("#FFE970"),
		Offline: lipgloss.Color("#FF3FD1"),
		Dim:     lipgloss.Color("#02030F"),
	},
	// 48: CRT Glow
	{
		Border:  lipgloss.Color("#182432"),
		Title:   lipgloss.Color("#F5F5DC"),
		Info:    lipgloss.Color("#00B0FF"),
		Meter:   lipgloss.Color("#76FF03"),
		Log:     lipgloss.Color("#101824"),
		Help:    lipgloss.Color("#090C16"),
		Online:  lipgloss.Color("#76FF03"),
		Offline: lipgloss.Color("#FF5252"),
		Dim:     lipgloss.Color("#030308"),
	},
	// 49: Floppy Diskette
	{
		Border:  lipgloss.Color("#365C8A"),
		Title:   lipgloss.Color("#FFFFFF"),
		Info:    lipgloss.Color("#4E82C4"),
		Meter:   lipgloss.Color("#F8F2DF"),
		Log:     lipgloss.Color("#273650"),
		Help:    lipgloss.Color("#1B2742"),
		Online:  lipgloss.Color("#4E82C4"),
		Offline: lipgloss.Color("#365C8A"),
		Dim:     lipgloss.Color("#02040A"),
	},
	// 50: Synth Arcade
	{
		Border:  lipgloss.Color("#2E1F63"),
		Title:   lipgloss.Color("#FDF5FF"),
		Info:    lipgloss.Color("#00FFE0"),
		Meter:   lipgloss.Color("#FF57C1"),
		Log:     lipgloss.Color("#20134A"),
		Help:    lipgloss.Color("#140B33"),
		Online:  lipgloss.Color("#00FFE0"),
		Offline: lipgloss.Color("#FF8A3C"),
		Dim:     lipgloss.Color("#04010A"),
	},
	// 51: 8-Bit Dusk
	{
		Border:  lipgloss.Color("#5A3E8E"),
		Title:   lipgloss.Color("#FFE4C6"),
		Info:    lipgloss.Color("#C459BF"),
		Meter:   lipgloss.Color("#F79C67"),
		Log:     lipgloss.Color("#312854"),
		Help:    lipgloss.Color("#211C3C"),
		Online:  lipgloss.Color("#F79C67"),
		Offline: lipgloss.Color("#C459BF"),
		Dim:     lipgloss.Color("#05040D"),
	},
	// 52: Retro Electro
	{
		Border:  lipgloss.Color("#2F5BFF"),
		Title:   lipgloss.Color("#F9F9FF"),
		Info:    lipgloss.Color("#FFDF40"),
		Meter:   lipgloss.Color("#FF2079"),
		Log:     lipgloss.Color("#181735"),
		Help:    lipgloss.Color("#101024"),
		Online:  lipgloss.Color("#2F5BFF"),
		Offline: lipgloss.Color("#FF2079"),
		Dim:     lipgloss.Color("#020208"),
	},
	// 53: Cassette Blaze
	{
		Border:  lipgloss.Color("#541731"),
		Title:   lipgloss.Color("#FFF1DC"),
		Info:    lipgloss.Color("#FF7A3A"),
		Meter:   lipgloss.Color("#FF3040"),
		Log:     lipgloss.Color("#3A1129"),
		Help:    lipgloss.Color("#260C1E"),
		Online:  lipgloss.Color("#FFC15A"),
		Offline: lipgloss.Color("#FF3040"),
		Dim:     lipgloss.Color("#080309"),
	},
	// 54: Laser Arcade
	{
		Border:  lipgloss.Color("#102853"),
		Title:   lipgloss.Color("#F8FBFF"),
		Info:    lipgloss.Color("#09FBD3"),
		Meter:   lipgloss.Color("#FF007C"),
		Log:     lipgloss.Color("#0C1C3D"),
		Help:    lipgloss.Color("#08102A"),
		Online:  lipgloss.Color("#09FBD3"),
		Offline: lipgloss.Color("#FF007C"),
		Dim:     lipgloss.Color("#02030D"),
	},
	// 55: Retro Waveform
	{
		Border:  lipgloss.Color("#281C47"),
		Title:   lipgloss.Color("#F7F3FF"),
		Info:    lipgloss.Color("#8BE9FD"),
		Meter:   lipgloss.Color("#FF6EC7"),
		Log:     lipgloss.Color("#1C1333"),
		Help:    lipgloss.Color("#120C24"),
		Online:  lipgloss.Color("#8BE9FD"),
		Offline: lipgloss.Color("#FF6EC7"),
		Dim:     lipgloss.Color("#05030A"),
	},
	// 56: Neon Cartridge
	{
		Border:  lipgloss.Color("#181E47"),
		Title:   lipgloss.Color("#F0F5FF"),
		Info:    lipgloss.Color("#00A3FF"),
		Meter:   lipgloss.Color("#FF4FD8"),
		Log:     lipgloss.Color("#101333"),
		Help:    lipgloss.Color("#0A0A22"),
		Online:  lipgloss.Color("#00FF9D"),
		Offline: lipgloss.Color("#FF4FD8"),
		Dim:     lipgloss.Color("#04020A"),
	},
	// 57: Analog Sunset
	{
		Border:  lipgloss.Color("#4A2147"),
		Title:   lipgloss.Color("#FFF3D9"),
		Info:    lipgloss.Color("#FF8A4A"),
		Meter:   lipgloss.Color("#FF4A7A"),
		Log:     lipgloss.Color("#341735"),
		Help:    lipgloss.Color("#231024"),
		Online:  lipgloss.Color("#FFC94A"),
		Offline: lipgloss.Color("#FF4A7A"),
		Dim:     lipgloss.Color("#050308"),
	},
	// 58: Pixel Noir
	{
		Border:  lipgloss.Color("#3A3A54"),
		Title:   lipgloss.Color("#F2F2FF"),
		Info:    lipgloss.Color("#64648A"),
		Meter:   lipgloss.Color("#25253A"),
		Log:     lipgloss.Color("#1A1A2B"),
		Help:    lipgloss.Color("#11111F"),
		Online:  lipgloss.Color("#64648A"),
		Offline: lipgloss.Color("#25253A"),
		Dim:     lipgloss.Color("#020205"),
	},
}
